name: Release Please

on:
  workflow_dispatch: 
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # Changelog & PR
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      # Publish steps
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}